# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.CharField(default='More to come later', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='More to come later', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_summary',
            field=models.CharField(default='More to come later', max_length=200),
            preserve_default=False,
        ),
    ]
